### ISSUE TITLE
multiple sensors

### ISSUE THREAD

**Issue by kubs0ne** [DFRobot/DFRobot_RaspberryPi_A02YYUW#1]
Hello, I would like to connect multiple sensors through an usb-uart converter. I'm doing it on Jetson AGX XAVIER. How do I change the pins to read data in the python script? I saw that in the arduino example there is something as `SoftwareSerial mySerial(11,10); // RX, TX`. Could I do a similar thing in python?
Regards

**Comment by kadlu** [comment]
Hi kubsOne
I managed to connect multiple sensors through usb-uart converters. I used cp2102 chips like this one: https://components101.com/modules/cp2102-uart-module. You can program an individual serial to each chip and identify the port with this information. In addition you only have to adjust the init of class DFRobot_A02_Distance to hand-over the port adress for each sensor. After that it should work. 
In addition i had to add a line at the beginning of the function measure() i added self.ser.write(b'1').

Hope that helps
